# This is intended as the simplest way to get a complete ArchivesSpace system up and running on a single instance using Docker.
# See also: https://docs.archivesspace.org/administration/docker/

services:
  app:
    image: archivesspace/archivesspace:4.2.0@sha256:7bd8aa78412715044df84450bf3925b4e8a36a55fe5a11c4710e26978f82c73b
    platform: linux/x86_64
    container_name: archivesspace
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - solr
    volumes:
      - app-data:/archivesspace/data
      - ./plugins:/archivesspace/plugins
      - ./config:/archivesspace/config
      - ./locales:/archivesspace/locales
      - ./stylesheets:/archivesspace/stylesheets

  db:
    image: mysql:8.4.9@sha256:c36050afdca850f23cef85703f84c7531a5ae155a11b5ee1c60acb09937c4084
    platform: linux/x86_64
    cap_add:
      - SYS_NICE
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_buffer_pool_size=1G  --innodb_buffer_pool_instances=1 --log_bin_trust_function_creators=1
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  db-backup:
    image: databack/mysql-backup:1.4.0@sha256:9a9a12dc942c370040ced1d43ab9f7d1162e9fde7f38b0f7749c3516d79a812c
    platform: linux/x86_64
    container_name: db-backup
    restart: unless-stopped
    user: "0"
    env_file:
      - .env
    environment:
      DB_DUMP_CRON: "0 2 * * *" # UTC
      DB_DUMP_TARGET: /db
      DB_SERVER: db
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD} # from .env
    command: dump
    volumes:
      - ./backups:/db
    depends_on:
      - db

  solr:
    image: archivesspace/solr:4.2.0@sha256:6bbea2a9464fb4a6200f9c70a2b05537816f8c3e3c8205b67a593f7113862523
    platform: linux/x86_64
    container_name: solr
    restart: unless-stopped
    env_file:
      - .env
    command:
      - solr-precreate
      - archivesspace
      - /opt/solr/server/solr/configsets/archivesspace
    volumes:
      - solr-data:/var/solr

  traefik:
    image: traefik:v3.7.1@sha256:6b9cbca6fac42ab0075f5437d8dc1685cfd188626d8d515839ea94f8b6271c42
    restart: always
    container_name: traefik
    command: >-
      --api.insecure=true
      --api.dashboard=true
      --api.debug=true
      --ping=true
      --entryPoints.http.address=:80
      --entryPoints.http.forwardedHeaders.trustedIPs=172.0.0.0/8
      --entryPoints.http.transport.respondingTimeouts.readTimeout=3600
      --providers.file.filename=/etc/traefik/config.yaml
      --providers.file.watch=true
      --providers.docker=true
      --providers.docker.network=default
      --providers.docker.exposedByDefault=false
      --experimental.localPlugins.captcha-protect.moduleName=github.com/libops/captcha-protect
    environment:
      TURNSTILE_SITE_KEY: ${TURNSTILE_SITE_KEY:-1x00000000000000000000AA}
      TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY:-1x0000000000000000000000000000000AA}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    ports:
      - 8200:80
    volumes:
      - ./conf/traefik/plugins/captcha-protect:/plugins-local/src/github.com/libops/captcha-protect:ro
      - ./conf/traefik/config.tmpl:/etc/traefik/config.yaml:ro
      - ./conf/traefik/challenge.tmpl.html:/challenge.tmpl.html:ro
      - /var/run/docker.sock:/var/run/docker.sock:z
      - traefik-data:/data
    healthcheck:
      test: traefik healthcheck --ping
      start_period: 5s
    depends_on:
      app:
        condition: service_healthy

volumes:
  app-data:
  db-data:
  solr-data:
  traefik-data:
