# This is intended as the simplest way to get a complete ArchivesSpace system up and running on a single instance using Docker.
# See also: https://docs.archivesspace.org/administration/docker/

services:
  app:
    image: archivesspace/archivesspace:4.2.0@sha256:7bd8aa78412715044df84450bf3925b4e8a36a55fe5a11c4710e26978f82c73b
    platform: linux/x86_64
    container_name: archivesspace
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
      - solr
    volumes:
      - app-data:/archivesspace/data
      - ./plugins:/archivesspace/plugins
      - ./config:/archivesspace/config
      - ./locales:/archivesspace/locales
      - ./stylesheets:/archivesspace/stylesheets

  db:
    image: mysql:8.4.9@sha256:c36050afdca850f23cef85703f84c7531a5ae155a11b5ee1c60acb09937c4084
    platform: linux/x86_64
    cap_add:
      - SYS_NICE
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_buffer_pool_size=1G  --innodb_buffer_pool_instances=1 --log_bin_trust_function_creators=1
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  db-backup:
    image: databack/mysql-backup:1.4.0@sha256:9a9a12dc942c370040ced1d43ab9f7d1162e9fde7f38b0f7749c3516d79a812c
    platform: linux/x86_64
    container_name: db-backup
    restart: unless-stopped
    user: "0"
    env_file:
      - .env
    environment:
      DB_DUMP_CRON: "0 2 * * *" # UTC
      DB_DUMP_TARGET: /db
      DB_SERVER: db
      DB_USER: root
      DB_PASS: ${MYSQL_ROOT_PASSWORD} # from .env
    command: dump
    volumes:
      - ./backups:/db
    depends_on:
      - db

  solr:
    image: archivesspace/solr:4.2.0@sha256:6bbea2a9464fb4a6200f9c70a2b05537816f8c3e3c8205b67a593f7113862523
    platform: linux/x86_64
    container_name: solr
    restart: unless-stopped
    env_file:
      - .env
    command:
      - solr-precreate
      - archivesspace
      - /opt/solr/server/solr/configsets/archivesspace
    volumes:
      - solr-data:/var/solr

  proxy:
    image: nginx:1.31.0@sha256:06aa3d7be10bc6307990c81bdca075793132e9163391abc370c015e344e23128
    platform: linux/x86_64
    container_name: proxy
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - app
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./proxy-config:/etc/nginx/conf.d/

volumes:
  app-data:
  db-data:
  solr-data:
